#!/usr/bin/env python3
"""Verify source identity, EPUB/PDF fidelity, and absence of duplicate leaves.

The PDF was generated by Calibre from the same Gutenberg transcription as the
EPUB.  Agreement is therefore evidence of extraction fidelity, not a second
witness to correctness.  The duplicate-page probe includes its required
positive control by comparing the first content page with itself.

Usage:
    ocr/.venv/bin/python3 scripts/verify_sources.py \
        source/pg59-images-3.pdf work/raw.md
"""

from __future__ import annotations

import difflib
import re
import sys
from pathlib import Path

import pymupdf


EXPECTED_PDF_PAGES = 35
EXPECTED_CONTENT_TOKENS = 25_391
MIN_FIDELITY_RATIO = 0.999


def normalize_page(text: str) -> str:
    lines = [line.strip() for line in text.splitlines()]
    lines = [line for line in lines if line and not re.fullmatch(r"\d+", line)]
    return " ".join(" ".join(lines).split())


def tokens(text: str) -> list[str]:
    text = re.sub(r"(?m)^#{1,6}\s+", "", text)
    text = re.sub(r"(?m)^<!-- page \d+ -->\s*$", "", text)
    text = re.sub(r"(?m)^\d+\s*$", "", text)
    return re.findall(r"[\w’'-]+|[^\w\s]", text, flags=re.UNICODE)


def main() -> int:
    if len(sys.argv) != 3:
        raise SystemExit(__doc__)
    pdf_path = Path(sys.argv[1])
    raw_path = Path(sys.argv[2])
    doc = pymupdf.open(pdf_path)
    if doc.page_count != EXPECTED_PDF_PAGES:
        raise AssertionError(f"expected {EXPECTED_PDF_PAGES} PDF pages, found {doc.page_count}")

    metadata = doc.metadata
    if metadata.get("producer") != "calibre 9.5.0":
        raise AssertionError(f"unexpected PDF producer: {metadata.get('producer')!r}")
    pages = [normalize_page(page.get_text()) for page in doc]

    # Positive control: the probe must recognize identity before a zero is used.
    control = difflib.SequenceMatcher(None, pages[7], pages[7], autojunk=False).ratio()
    if control != 1.0:
        raise AssertionError(f"duplicate-scan positive control failed: {control}")
    print("POSITIVE CONTROL duplicate scan: PDF page 8 vs itself = 1.000")

    candidates: list[tuple[int, int, float]] = []
    for left in range(len(pages)):
        for offset in (1, 2, 3, 4, 5, 6, 16):
            right = left + offset
            if right >= len(pages) or not pages[left] or not pages[right]:
                continue
            ratio = difflib.SequenceMatcher(
                None, pages[left], pages[right], autojunk=True
            ).ratio()
            if ratio > 0.85:
                candidates.append((left + 1, right + 1, ratio))
    if candidates:
        raise AssertionError(f"possible duplicate pages: {candidates!r}")
    print("DUPLICATE SCAN: none at offsets 1-6 or 16 above ratio 0.85")

    pdf_text = "\n".join(page.get_text() for page in doc)
    pdf_text = pdf_text[
        pdf_text.index("PREFATORY NOTE BY THE AUTHOR") :
        pdf_text.index("*** END OF THE PROJECT GUTENBERG")
    ]
    raw_text = raw_path.read_text(encoding="utf-8")
    raw_text = raw_text[raw_text.index("## PREFATORY NOTE BY THE AUTHOR") :]
    raw_tokens = tokens(raw_text)
    pdf_tokens = tokens(pdf_text)
    if len(raw_tokens) != EXPECTED_CONTENT_TOKENS:
        raise AssertionError(f"EPUB token count changed: {len(raw_tokens)}")
    matcher = difflib.SequenceMatcher(None, raw_tokens, pdf_tokens, autojunk=False)
    ratio = matcher.ratio()
    if ratio < MIN_FIDELITY_RATIO:
        raise AssertionError(f"EPUB/PDF token fidelity too low: {ratio:.6f}")
    differences = [
        (tag, raw_tokens[i1:i2], pdf_tokens[j1:j2])
        for tag, i1, i2, j1, j2 in matcher.get_opcodes()
        if tag != "equal"
    ]
    expected_differences = [
        ("replace", ["avail--rather"], ["avail--", "rather"]),
        *[("delete", ["*"], []) for _ in range(16)],
    ]
    if differences != expected_differences:
        raise AssertionError(f"unexpected EPUB/PDF token differences: {differences!r}")
    print(
        f"SOURCE FIDELITY: EPUB {len(raw_tokens):,} tokens; "
        f"PDF {len(pdf_tokens):,}; SequenceMatcher ratio {ratio:.6f}"
    )
    print("LIMIT: both are renderings of one Gutenberg transcription, not independent witnesses")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
