#!/usr/bin/env python3
"""Build Darwin's 1859 Origin of Species from the supplied PG EPUB.

The EPUB is the structured source.  The sibling PDF was generated by Calibre
from the same Project Gutenberg transcription, so it can establish fidelity to
that rendering but is not an independent witness to correctness.

The one plate omitted by both Gutenberg files was acquired by the host on
2026-08-09 from Wikimedia Commons, public-domain file
"On_the_Origin_of_Species_diagram.PNG":
https://upload.wikimedia.org/wikipedia/commons/7/7b/On_the_Origin_of_Species_diagram.PNG
It is credited to Darwin, On the Origin of Species (1859), pp. 116–117. The
hash, byte size, and pixel dimensions below pin the exact second-hand scan.

Selection policy:
  * retain Darwin's title, subtitle, epigraphs, dated authorial front matter,
    introduction, all fourteen chapters, chapter synopses, italics,
    superscripts, and the geological table;
  * omit the Gutenberg wrapper and edition selector, bibliographic title-page
    furniture, contents/detailed contents, index, and licence;
  * restore Darwin's branching diagram at the printed pp. 116–117 position
    from the acquired public-domain scan, whose identity is asserted below.

All source identities, supported markup, structural counts, chapter sequence,
and word/number-token fidelity are asserted.  Re-running against a changed
source fails rather than silently producing a different selection.

Usage:
    ocr/.venv/bin/python3 build_darwin.py EPUB PDF OUTPUT.md
"""

from __future__ import annotations

import hashlib
import io
import re
import shutil
import sys
import zipfile
from collections import Counter
from pathlib import Path

import pymupdf
from lxml import etree


NS = {"x": "http://www.w3.org/1999/xhtml"}
EPUB_SHA256 = "45a58497f8a0234c1f79a701012367d63a43db5a225d9dc19924abd8c91f532a"
PDF_SHA256 = "140ae2bdac6e1fe2bcc1d5da64f1a74e6b698a7ac2646d9389ca7baa9b5e83c0"
DIAGRAM_SHA256 = "356d6dcf65cc77bf62a29632ac54b4699b7eeace27af22413bfc0651c62a1477"
DIAGRAM_SOURCE_URL = "https://upload.wikimedia.org/wikipedia/commons/7/7b/On_the_Origin_of_Species_diagram.PNG"
DIAGRAM_LICENSE = "public domain"
DIAGRAM_ACQUIRED = "2026-08-09"
DIAGRAM_BYTES = 4_980_112
DIAGRAM_WIDTH = 2_497
DIAGRAM_HEIGHT = 1_946
DIAGRAM_SOURCE = Path(__file__).resolve().parent / "acquired/darwin-diagram-source.png"
DIAGRAM_OUTPUT_NAME = "darwin-branching-diagram-1859.png"
DIAGRAM_ALT = "Darwin's branching diagram of divergence of character"
DIAGRAM_MARKDOWN = f"![{DIAGRAM_ALT}](images/{DIAGRAM_OUTPUT_NAME})"
TITLE = "On the Origin of Species"
EXPECTED_PARAGRAPHS = 694
EXPECTED_ITALICS = 162  # four retained front-matter <i>s plus 158 in the work
EXPECTED_SUPERSCRIPTS = 68
EXPECTED_PAGE_ANCHORS = 505
EXPECTED_CHAPTERS = [
    "CHAPTER I. VARIATION UNDER DOMESTICATION.",
    "CHAPTER II. VARIATION UNDER NATURE.",
    "CHAPTER III. STRUGGLE FOR EXISTENCE.",
    "CHAPTER IV. NATURAL SELECTION.",
    "CHAPTER V. LAWS OF VARIATION.",
    "CHAPTER VI. DIFFICULTIES ON THEORY.",
    "CHAPTER VII. INSTINCT.",
    "CHAPTER VIII. HYBRIDISM.",
    "CHAPTER IX. ON THE IMPERFECTION OF THE GEOLOGICAL RECORD.",
    "CHAPTER X. ON THE GEOLOGICAL SUCCESSION OF ORGANIC BEINGS.",
    "CHAPTER XI. GEOGRAPHICAL DISTRIBUTION.",
    "CHAPTER XII. GEOGRAPHICAL DISTRIBUTION—continued.",
    "CHAPTER XIII. MUTUAL AFFINITIES OF ORGANIC BEINGS: MORPHOLOGY: EMBRYOLOGY: RUDIMENTARY ORGANS.",
    "CHAPTER XIV. RECAPITULATION AND CONCLUSION.",
]
def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def local_name(node: etree._Element) -> str:
    return etree.QName(node).localname


def norm(text: str) -> str:
    return re.sub(r"\s+", " ", text.replace("\xa0", " ")).strip()


def tokens(text: str) -> list[str]:
    return re.findall(r"[^\W\d_]+(?:['\u2019][^\W\d_]+)*|\d+", text.lower(), re.UNICODE)


def read_chunks(epub: Path) -> dict[int, etree._Element]:
    with zipfile.ZipFile(epub) as zf:
        names: dict[int, str] = {}
        for name in zf.namelist():
            match = re.search(r"_1228-h-(\d+)\.htm\.xhtml$", name)
            if match:
                names[int(match.group(1))] = name
        assert sorted(names) == list(range(18)), f"EPUB XHTML chunks changed: {sorted(names)}"
        return {
            number: etree.parse(io.BytesIO(zf.read(name))).getroot()
            for number, name in names.items()
        }


def inline(node: etree._Element, stats: Counter[str]) -> str:
    out = [node.text or ""]
    for child in node:
        tag = local_name(child)
        if tag == "a":
            # Selected chapters contain only empty page/section targets.  A
            # text-bearing link would be a new convention requiring judgment.
            assert not norm("".join(child.itertext())), "text-bearing link in selected work"
            stats["page_anchors"] += 1
            piece = ""
        elif tag == "i":
            stats["italics"] += 1
            body = inline(child, stats)
            piece = f"*{body.strip()}*" if body.strip() else ""
        elif tag == "small":
            piece = inline(child, stats)
        elif tag == "sup":
            stats["superscripts"] += 1
            body = inline(child, stats).strip()
            assert body and not list(child), "unexpected superscript structure"
            piece = f"<sup>{body}</sup>"
        elif tag == "br":
            piece = " "
        else:
            raise AssertionError(
                f"unhandled inline <{tag}> in {norm(''.join(node.itertext()))[:100]!r}"
            )
        out.append(piece)
        out.append(child.tail or "")
    return norm("".join(out))


def visible_text(node: etree._Element) -> str:
    return norm("".join(node.itertext()))


def build(epub: Path) -> tuple[str, list[str], Counter[str]]:
    chunks = read_chunks(epub)
    stats: Counter[str] = Counter()
    blocks: list[str] = []
    source_blocks: list[str] = []

    # Title and authorial front matter.  Direct-child positions are asserted so
    # the selection cannot drift into the adjacent edition selector or contents.
    front_bodies = chunks[0].xpath("//x:body", namespaces=NS)
    assert len(front_bodies) == 1
    front = list(front_bodies[0])
    assert [local_name(node) for node in front[4:15]] == [
        "h1", "h4", "h3", "h2", "h4", "hr", "p", "p", "p", "p", "p"
    ]
    assert visible_text(front[4]) == TITLE
    assert visible_text(front[16]) == "Contents"
    assert visible_text(front[18]) == "DETEAILED CONTENTS. ON THE ORIGIN OF SPECIES."

    title = inline(front[4], stats)
    subtitle_a = inline(front[5], stats)
    subtitle_b = inline(front[6], stats)
    author = inline(front[7], stats)
    epigraph_1 = inline(front[10], stats)
    epigraph_1_by = inline(front[11], stats)
    epigraph_2 = inline(front[12], stats)
    epigraph_2_by = inline(front[13], stats)
    date_line = inline(front[14], stats)
    source_blocks.extend([
        title, subtitle_a, subtitle_b, author,
        epigraph_1, epigraph_1_by, epigraph_2, epigraph_2_by, date_line,
    ])
    blocks.extend([
        f"# {title}",
        f"*{subtitle_a} {subtitle_b}*",
        f"*{author}*",
        f"> {epigraph_1}\n>\n> — {epigraph_1_by}",
        f"> {epigraph_2}\n>\n> — {epigraph_2_by}",
        date_line,
    ])

    # The first XHTML work chunk contains a duplicate half-title div followed
    # by the complete authorial introduction div.
    intro_body = chunks[1].xpath("//x:body", namespaces=NS)[0]
    intro_divs = list(intro_body)
    assert len(intro_divs) == 2
    assert visible_text(intro_divs[0]) == "ON THE ORIGIN OF SPECIES."
    assert local_name(intro_divs[1]) == "div"

    chapter_headings: list[str] = []
    selected_containers = [intro_divs[1]]
    for number in range(2, 16):
        body = chunks[number].xpath("//x:body", namespaces=NS)[0]
        children = list(body)
        assert len(children) == 1 and local_name(children[0]) == "div", number
        selected_containers.append(children[0])

    for container_number, container in enumerate(selected_containers):
        direct = list(container)
        assert direct and local_name(direct[0]) == "h2"
        heading = inline(direct[0], stats)
        heading_plain = heading.replace("*", "")
        if container_number == 0:
            assert heading_plain == "INTRODUCTION."
            blocks.append("## INTRODUCTION")
        else:
            chapter_headings.append(heading_plain)
            blocks.append(f"## {heading}")
        source_blocks.append(heading_plain)

        for node in direct[1:]:
            tag = local_name(node)
            if tag == "p":
                rendered = inline(node, stats)
                assert rendered, f"empty paragraph in section {heading_plain}"
                blocks.append(rendered)
                source_blocks.append(visible_text(node))
                stats["paragraphs"] += 1
                if rendered.startswith("The accompanying diagram will aid us"):
                    assert stats["diagram_references"] == 0
                    blocks.append(DIAGRAM_MARKDOWN)
                    stats["diagram_references"] += 1
            elif tag == "pre":
                assert container_number == 9, "preformatted block outside Chapter IX"
                raw = (node.text or "").strip("\n")
                assert "Palæozoic strata" in raw and "72,584" not in raw
                lines = [line.strip() for line in raw.splitlines() if line.strip()]
                assert lines[0] == "Feet" and len(lines) == 4, lines
                rows = []
                for line in lines[1:]:
                    match = re.fullmatch(r"(.+?)\.{3,}([\d,]+\.)", line)
                    assert match, f"unexpected geological table row: {line!r}"
                    rows.append((match.group(1), match.group(2)))
                blocks.append("\n".join([
                    "| | Feet |",
                    "|---|---:|",
                    *(f"| {label} | {value} |" for label, value in rows),
                ]))
                source_blocks.append(visible_text(node))
                stats["pre_blocks"] += 1
            else:
                raise AssertionError(f"unhandled block <{tag}> in {heading_plain}")

    assert chapter_headings == EXPECTED_CHAPTERS, chapter_headings
    assert stats["paragraphs"] == EXPECTED_PARAGRAPHS, stats
    assert stats["italics"] == EXPECTED_ITALICS, stats
    assert stats["superscripts"] == EXPECTED_SUPERSCRIPTS, stats
    assert stats["page_anchors"] == EXPECTED_PAGE_ANCHORS, stats
    assert stats["pre_blocks"] == 1 and stats["diagram_references"] == 1, stats

    markdown = "\n\n".join(blocks) + "\n"
    assert markdown.count("\n# ") == 0 and markdown.startswith(f"# {TITLE}\n")
    assert markdown.count("\n## ") == 15  # introduction plus fourteen chapters
    assert "Project Gutenberg" not in markdown
    assert "DETEAILED CONTENTS" not in markdown and "\n## INDEX" not in markdown
    assert "href=" not in markdown and "<a" not in markdown
    assert markdown.count(DIAGRAM_MARKDOWN) == 1

    # This is one plate reused conceptually, not three missing figures. Chapter
    # X refers back to it once, and Chapter XIII does so twice. None introduces
    # a second diagram or asks for a different image.
    assert markdown.count("turn to the diagram in the fourth chapter") == 1
    assert markdown.count("turn to the diagram illustrating the action") == 1
    assert markdown.count("referring to the diagram in the fourth chapter") == 1

    # Markdown punctuation and the restored figure's descriptive alt text may
    # differ; the selected human-readable word/number stream may not.
    visible_markdown = markdown.replace(DIAGRAM_MARKDOWN, "")
    visible_markdown = re.sub(r"</?sup>", "", visible_markdown)
    output_tokens = tokens(visible_markdown)
    expected_tokens = tokens(" ".join(source_blocks))
    if output_tokens != expected_tokens:
        mismatch = next(
            (i for i, pair in enumerate(zip(output_tokens, expected_tokens)) if pair[0] != pair[1]),
            min(len(output_tokens), len(expected_tokens)),
        )
        raise AssertionError(
            "Markdown conversion added, removed, or reordered source tokens at "
            f"token {mismatch}: output={output_tokens[mismatch:mismatch + 12]!r}, "
            f"source={expected_tokens[mismatch:mismatch + 12]!r}"
        )
    return markdown, source_blocks, stats


def verify_pdf(pdf: Path, source_blocks: list[str]) -> int:
    doc = pymupdf.open(pdf)
    assert len(doc) == 192, f"expected 192-page sibling PDF, found {len(doc)}"
    assert TITLE in norm(doc[4].get_text("text")), "PDF p.5 title mismatch"
    pdf_pages: list[str] = []
    for page in doc:
        lines = page.get_text("text").splitlines()
        # Calibre emits the printed running page number as the first text line.
        # Removing it lets paragraphs crossing a rendered page remain a single
        # comparison stream.  This is layout furniture, not source prose.
        if lines and re.fullmatch(r"\s*[ivxlcdm]+\.?|\s*\d+\.?", lines[0], re.I):
            lines = lines[1:]
        pdf_pages.append("\n".join(lines))
    pdf_tokens = tokens(" ".join(pdf_pages))
    witness = " " + " ".join(pdf_tokens) + " "

    # Each selected source block is independently sought in the complete PDF
    # stream because the output deliberately skips contents and index blocks
    # that intervene in the PDF.  Short headings can recur; prose blocks cannot.
    missing: list[str] = []
    checked = 0
    for block in source_blocks:
        block_tokens = tokens(block)
        if len(block_tokens) < 5:
            continue
        checked += 1
        needle = " " + " ".join(block_tokens) + " "
        if needle not in witness:
            missing.append(norm(block)[:100])
    assert not missing, f"{len(missing)} selected blocks absent from PDF witness: {missing[:5]}"

    # Both supplied renderings omit the figure itself, not merely its HTML tag.
    for page in doc[44:50]:
        assert not page.get_images(full=True), "unexpected raster figure on PDF pp.45-50"
        drawings = page.get_drawings()
        assert len(drawings) == 1 and drawings[0]["type"] == "f" \
            and drawings[0]["fill"] == (1.0, 1.0, 1.0), (
                "unexpected vector content on PDF pp.45-50"
            )
    return checked


def main() -> int:
    if len(sys.argv) != 4:
        print(__doc__.strip(), file=sys.stderr)
        return 2
    epub, pdf, output = map(Path, sys.argv[1:])
    assert sha256(epub) == EPUB_SHA256, "supplied EPUB changed"
    assert sha256(pdf) == PDF_SHA256, "supplied PDF changed"
    assert DIAGRAM_SOURCE.stat().st_size == DIAGRAM_BYTES, "acquired diagram size changed"
    assert sha256(DIAGRAM_SOURCE) == DIAGRAM_SHA256, "acquired diagram changed"
    diagram_pixmap = pymupdf.Pixmap(str(DIAGRAM_SOURCE))
    assert (diagram_pixmap.width, diagram_pixmap.height) == (
        DIAGRAM_WIDTH, DIAGRAM_HEIGHT
    ), "acquired diagram dimensions changed"
    markdown, source_blocks, stats = build(epub)
    pdf_blocks = verify_pdf(pdf, source_blocks)
    images = output.parent / "images"
    images.mkdir(parents=True, exist_ok=True)
    diagram_output = images / DIAGRAM_OUTPUT_NAME
    shutil.copyfile(DIAGRAM_SOURCE, diagram_output)
    assert diagram_output.stat().st_size == DIAGRAM_BYTES
    assert sha256(diagram_output) == DIAGRAM_SHA256
    output.write_text(markdown, encoding="utf-8")
    print(f"wrote {output}: {len(markdown):,} chars, {len(markdown.split()):,} words")
    print(", ".join(f"{key}={value}" for key, value in sorted(stats.items())))
    print(f"PDF rendered witness: {pdf_blocks} selected blocks matched")
    print("correctness: not established; EPUB and PDF share one PG transcription")
    print(f"diagram: {diagram_output} ({DIAGRAM_WIDTH}x{DIAGRAM_HEIGHT}, sha256 verified)")
    print("completeness: all fourteen chapters and the one referenced plate are present")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
