#!/usr/bin/env python3
"""Build Maimonides' Guide for the Perplexed from PG 73584's EPUB.

The EPUB is the structured source.  The sibling PDF was generated by Calibre
from the same Project Gutenberg transcription, so it is a rendered witness and
not an independent witness to correctness.

Apparatus policy:
  * omit Gutenberg boilerplate, title/edition matter, Friedlander's prefaces,
    life of Maimonides, literature survey, analysis, contents, indexes,
    colophon, and licence;
  * retain Maimonides' dedicatory letter and authorial introduction, followed
    by all three parts and their 76, 48, and 54 chapters;
  * retain bracketed interpolations and source italics within the translation.

All source boundaries, chapter sequences, supported markup, and token fidelity
are asserted.  Re-running against a changed source fails instead of silently
producing a differently selected text.

Usage:
    python3 convert_maimonides_epub.py SOURCE.epub OUTPUT.md
"""

from __future__ import annotations

import io
import re
import sys
import zipfile
from collections import Counter
from pathlib import Path

from lxml import etree


TITLE = "THE GUIDE FOR THE PERPLEXED"
CONTENT_CHUNKS = [1, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
PART_CHAPTERS = {"PART I": 76, "PART II": 48, "PART III": 54}
ROMAN = [
    "I", "II", "III", "IV", "V", "VI", "VII", "VIII", "IX", "X",
    "XI", "XII", "XIII", "XIV", "XV", "XVI", "XVII", "XVIII", "XIX", "XX",
    "XXI", "XXII", "XXIII", "XXIV", "XXV", "XXVI", "XXVII", "XXVIII", "XXIX", "XXX",
    "XXXI", "XXXII", "XXXIII", "XXXIV", "XXXV", "XXXVI", "XXXVII", "XXXVIII", "XXXIX", "XL",
    "XLI", "XLII", "XLIII", "XLIV", "XLV", "XLVI", "XLVII", "XLVIII", "XLIX", "L",
    "LI", "LII", "LIII", "LIV", "LV", "LVI", "LVII", "LVIII", "LIX", "LX",
    "LXI", "LXII", "LXIII", "LXIV", "LXV", "LXVI", "LXVII", "LXVIII", "LXIX", "LXX",
    "LXXI", "LXXII", "LXXIII", "LXXIV", "LXXV", "LXXVI",
]
EXPECTED_PARAGRAPHS = 970
EXPECTED_RENDERED_ITALICS = 1_900
EXPECTED_SOURCE_ITALICS = 1_900
EXPECTED_CORRECTIONS = 93
EXPECTED_RENDERED_PAGE_MARKERS = 396
EXPECTED_SOURCE_PAGE_MARKERS = 581
EXPECTED_INTRO_SUBHEADS = [
    "[*Letter of the Author to his Pupil, R. Joseph Ibn Aknin.*]",
    "[*Prefatory Remarks.*]",
    "*Directions for the Study of this Work.*",
    "*Introductory Remarks.*",
]


def local_name(node: etree._Element) -> str:
    return etree.QName(node).localname


def norm(text: str) -> str:
    return re.sub(r"\s+", " ", text.replace("\xa0", " ")).strip()


def tokens(text: str) -> list[str]:
    return re.findall(r"[^\W\d_]+(?:['\u2019][^\W\d_]+)*|\d+", text.lower(), re.UNICODE)


def inline(node: etree._Element, stats: Counter[str]) -> str:
    """Render the selected XHTML inline vocabulary and remove page links."""
    out = [node.text or ""]
    for child in node:
        tag = local_name(child)
        classes = set((child.get("class") or "").split())
        if "pageNum" in classes:
            stats["page_markers"] += 1
            piece = ""
        elif tag == "i":
            stats["italics"] += 1
            body = inline(child, stats).strip()
            piece = f"*{body}*" if body else ""
        elif tag in {"span", "a"}:
            # Correction spans expose PG's adopted reading as visible text.
            # Links are flattened: in-page navigation breaks the reader.
            if "corr" in classes:
                stats["corrections"] += 1
            piece = inline(child, stats)
        else:
            raise AssertionError(f"unhandled inline element <{tag}> in {norm(''.join(node.itertext()))[:80]!r}")
        out.append(piece)
        out.append(child.tail or "")
    return norm("".join(out))


def numbered_chunk_names(zf: zipfile.ZipFile) -> dict[int, str]:
    found: dict[int, str] = {}
    for name in zf.namelist():
        match = re.search(r"-h-(\d+)\.htm\.xhtml$", name)
        if match:
            found[int(match.group(1))] = name
    expected_all = [0, 1, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 15, 17, 18, 19, 20, 21, 22, 23, 24]
    assert sorted(found) == expected_all, f"EPUB XHTML chunks changed: {sorted(found)}"
    return found


def selected_roots(epub: Path) -> list[etree._Element]:
    roots: list[etree._Element] = []
    with zipfile.ZipFile(epub) as zf:
        names = numbered_chunk_names(zf)
        for index in CONTENT_CHUNKS:
            root = etree.parse(io.BytesIO(zf.read(names[index]))).getroot()
            if index == 1:
                selected = root.xpath("//*[local-name()='div' and @id='introduction']")
                assert len(selected) == 1, "authorial introduction boundary not found"
                roots.extend(selected)
            else:
                selected = root.xpath(
                    "//*[local-name()='body']/*[local-name()='div']/*[local-name()='div' and @class='body']"
                )
                assert len(selected) == 1, f"chunk {index}: Guide body boundary not found"
                roots.extend(selected)
    assert len(roots) == len(CONTENT_CHUNKS)
    return roots


def convert(epub: Path) -> tuple[str, Counter[str]]:
    roots = selected_roots(epub)
    stats: Counter[str] = Counter()
    blocks = [f"# {TITLE}"]
    source_visible_blocks: list[str] = []
    chapters: dict[str, list[str]] = {part: [] for part in PART_CHAPTERS}
    intro_subheads: list[str] = []
    current_part: str | None = None

    # The selected span must not contain apparatus structures or figures.
    all_nodes = [node for root in roots for node in root.iter()]
    assert sum("pageNum" in set((node.get("class") or "").split()) for node in all_nodes) == EXPECTED_SOURCE_PAGE_MARKERS
    assert sum(local_name(node) == "i" for node in all_nodes) == EXPECTED_SOURCE_ITALICS
    forbidden = [
        node for node in all_nodes
        if local_name(node) in {"img", "table", "ol", "ul", "sup", "sub", "br"}
        or "footnote" in set((node.get("class") or "").split())
        or "noteRef" in set((node.get("class") or "").split())
    ]
    assert not forbidden, f"new figure/list/note/inline structure in selected text: {forbidden[0].attrib}"

    for root in roots:
        for node in root.iter():
            tag = local_name(node)
            if tag not in {"h2", "h3", "p"}:
                continue
            rendered = inline(node, stats)
            if not rendered:
                continue
            # Navigation-only nodes become blank after page markers are removed.
            if rendered == "Contents" and tag != "p":
                raise AssertionError("unexpected Contents heading in selected span")
            if rendered == "Contents":
                continue

            source_visible_blocks.append(rendered)
            if tag == "h2":
                heading = rendered.replace("*", "")
                if heading in PART_CHAPTERS:
                    current_part = heading
                    blocks.append(f"# {heading}")
                    stats["parts"] += 1
                elif heading == "INTRODUCTION":
                    # The first is the author's general introduction; Parts II
                    # and III each begin with their own introduction.
                    blocks.append("# INTRODUCTION" if current_part is None else "## INTRODUCTION")
                    stats["introductions"] += 1
                else:
                    match = re.fullmatch(r"CHAPTER ([IVXLCDM]+)", heading)
                    assert match and current_part, f"unexpected h2 {heading!r}"
                    chapters[current_part].append(match.group(1))
                    blocks.append(f"## {heading}")
                    stats["chapters"] += 1
            elif tag == "h3":
                assert current_part is None, f"unexpected h3 in {current_part}: {rendered!r}"
                intro_subheads.append(rendered)
                blocks.append(f"## {rendered}")
                stats["intro_subheads"] += 1
            else:
                blocks.append(rendered)
                stats["paragraphs"] += 1

    for part, count in PART_CHAPTERS.items():
        assert chapters[part] == ROMAN[:count], f"{part} chapter sequence changed: {chapters[part]}"
    assert intro_subheads == EXPECTED_INTRO_SUBHEADS, intro_subheads
    assert stats["parts"] == 3 and stats["introductions"] == 3 and stats["chapters"] == 178, stats
    assert stats["paragraphs"] == EXPECTED_PARAGRAPHS, stats
    assert stats["italics"] == EXPECTED_RENDERED_ITALICS, stats
    assert stats["corrections"] == EXPECTED_CORRECTIONS, stats
    assert stats["page_markers"] == EXPECTED_RENDERED_PAGE_MARKERS, stats

    markdown = "\n\n".join(blocks) + "\n"
    expected_tokens = tokens(" ".join(source_visible_blocks))
    output_without_added_title = "\n\n".join(blocks[1:]) + "\n"
    output_tokens = tokens(output_without_added_title)
    assert output_tokens == expected_tokens, "Markdown conversion added, removed, or reordered source tokens"
    assert "Project Gutenberg" not in markdown
    assert "THE LIFE OF MOSES MAIMONIDES" not in markdown
    assert "ANALYSIS OF THE GUIDE" not in markdown
    assert "href=" not in markdown and "<a" not in markdown
    return markdown, stats


def main() -> int:
    if len(sys.argv) != 3:
        print(__doc__.strip(), file=sys.stderr)
        return 2
    source, output = map(Path, sys.argv[1:])
    markdown, stats = convert(source)
    output.write_text(markdown, encoding="utf-8")
    print(f"wrote {output}: {len(markdown):,} chars, {len(markdown.split()):,} words")
    print(", ".join(f"{key}={value}" for key, value in sorted(stats.items())))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
